speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 2629

binary_sensor:
  - platform: ping
    name: "WAN Ping"
    host: 8.8.8.8
    count: 5
    scan_interval: 300

sensor:

  - platform: template
    sensors:
      wan_ping_avg:
        friendly_name: "WAN Ping"
        value_template: "{{ state_attr('binary_sensor.wan_ping', 'round_trip_time_avg') }}"
        unit_of_measurement: 'ms'
        icon_template: mdi:wan

      tpgrouter:
        friendly_name: Gateway
        value_template: >
          {% if is_state('device_tracker.ping_gateway', 'home') %}
            Connected
          {% else %}
            !no-reply, please check!
          {% endif %}
        icon_template: >
          {% if is_state('device_tracker.ping_gateway', 'home') %}
            mdi:network
          {% else %}
            mdi:network-off
          {% endif %}

      switch:
        friendly_name: Netgear v7610
        value_template: >
          {% if is_state('device_tracker.ping_switch_1', 'home') %}
            Connected
          {% else %}
            !no-reply, please check!
          {% endif %}
        icon_template: >
          {% if is_state('device_tracker.ping_switch_1', 'home') %}
            mdi:network
          {% else %}
            mdi:network-off
          {% endif %}

      wireless24:
        friendly_name: Telstra Gateway 5394
        value_template: >
          {% if is_state('device_tracker.ping_switch_2', 'home') %}
            Connected
          {% else %}
            !no-reply, please check!
          {% endif %}
        icon_template: >
          {% if is_state('device_tracker.ping_switch_2', 'home') %}
            mdi:access-point-network
          {% else %}
            mdi:access-point-network-off
          {% endif %}